# fly.toml app configuration file generated for veretragna-mysql on 2025-03-30T16:47:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'veretragna-mysql'
primary_region = 'mia'

[build]
  image = 'mysql:8'

[[vm]]
  size = 'shared-cpu-1x'
  cpus = 1
  memory = "512mb"

[processes]
  app = """--datadir /data/mysql \
    --mysql-native-password=ON \
    --max_connections=10 \
    --performance_schema=0 \
    --innodb_buffer_pool_size=16M"""

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE="veretragna"
  MYSQL_USER="veretragna_user"
