export const cities = [
  {
    name: 'Artigas',
    address: 'Artigas, Uruguay',
    imageUrl: 'cities/artigas.jpg',
    latitude: -30.4000,
    longitude: -56.4667,
    description: 'Artigas es una ciudad ubicada en el departamento de Artigas, Uruguay. Es conocida por su clima cálido y su rica cultura.',
  },
  {
    name: 'Canelones',
    address: 'Canelones, Uruguay',
    imageUrl: 'cities/canelones.jpg',
    latitude: -34.5222,
    longitude: -56.2778,
    description: 'Canelones es la capital del departamento de Canelones. Es una importante zona agrícola donde se producen frutas y verduras para todo el país.',
  },
  {
    name: 'Melo',
    address: 'Melo, Uruguay',
    imageUrl: 'cities/melo.jpg',
    latitude: -32.3700,
    longitude: -54.1800,
    description: 'Melo es la capital del departamento de Cerro Largo. Es una ciudad fronteriza con Brasil conocida por su patrimonio histórico y cultural.',
  },
  {
    name: 'Colonia del Sacramento',
    address: 'Colonia del Sacramento, Uruguay',
    imageUrl: 'cities/colonia-del-sacramento.jpg',
    latitude: -34.4628,
    longitude: -57.8400,
    description: 'Colonia del Sacramento es la capital del departamento de Colonia y Patrimonio de la Humanidad de la UNESCO. Su barrio histórico es famoso por su arquitectura colonial portuguesa.',
  },
  {
    name: 'Durazno',
    address: 'Durazno, Uruguay',
    imageUrl: 'cities/durazno.jpg',
    latitude: -33.3800,
    longitude: -56.5200,
    description: 'Durazno es la capital del departamento homónimo, ubicada en el centro geográfico de Uruguay. Es conocida por su Festival Nacional de Folclore.',
  },
  {
    name: 'Trinidad',
    address: 'Trinidad, Uruguay',
    imageUrl: 'cities/trinidad.jpg',
    latitude: -33.5144,
    longitude: -56.8969,
    description: 'Trinidad es la capital del departamento de Flores. Es una tranquila ciudad del interior con hermosas plazas y espacios verdes.',
  },
  {
    name: 'Florida',
    address: 'Florida, Uruguay',
    imageUrl: 'cities/florida.jpg',
    latitude: -34.0994,
    longitude: -56.2142,
    description: 'Florida es la capital del departamento de Florida. Es conocida por ser el lugar donde se declaró la independencia de Uruguay en 1825.',
  },
  {
    name: 'Minas',
    address: 'Minas, Uruguay',
    imageUrl: 'cities/minas.jpg',
    latitude: -34.3758,
    longitude: -55.2458,
    description: 'Minas es la capital del departamento de Lavalleja. Es famosa por sus paisajes serranos y el Cerro Arequita, un atractivo natural importante.',
  },
  {
    name: 'Maldonado',
    address: 'Maldonado, Uruguay',
    imageUrl: 'cities/maldonado.jpg',
    latitude: -34.9000,
    longitude: -54.9500,
    description: 'Maldonado es la capital del departamento de Maldonado. Es una ciudad turística próxima a Punta del Este con rica historia y patrimonio cultural.',
  },
  {
    name: 'Montevideo',
    address: 'Montevideo, Uruguay',
    imageUrl: 'cities/montevideo.jpg',
    latitude: -34.9011,
    longitude: -56.1645,
    description: 'Montevideo es la capital y ciudad más grande de Uruguay. Destaca por su rambla costera, sus playas, arquitectura histórica y su activa vida cultural.',
  },
  {
    name: 'Paysandú',
    address: 'Paysandú, Uruguay',
    imageUrl: 'cities/paysandu.jpg',
    latitude: -32.3214,
    longitude: -58.0756,
    description: 'Paysandú es la capital del departamento de Paysandú, ubicada a orillas del río Uruguay. Es conocida por su carnaval y sus aguas termales.',
  },
  {
    name: 'Fray Bentos',
    address: 'Fray Bentos, Uruguay',
    imageUrl: 'cities/fray-bentos.jpg',
    latitude: -33.1300,
    longitude: -58.3000,
    description: 'Fray Bentos es la capital del departamento de Río Negro. Su antiguo frigorífico es Patrimonio de la Humanidad y fue un centro industrial importante.',
  },
  {
    name: 'Rivera',
    address: 'Rivera, Uruguay',
    imageUrl: 'cities/rivera.jpg',
    latitude: -30.9053,
    longitude: -55.5508,
    description: 'Rivera es la capital del departamento de Rivera, situada en la frontera con Brasil. Es conocida por su comercio fronterizo y su cultura binacional.',
  },
  {
    name: 'Rocha',
    address: 'Rocha, Uruguay',
    imageUrl: 'cities/rocha.jpg',
    latitude: -34.4800,
    longitude: -54.3333,
    description: 'Rocha es la capital del departamento de Rocha. La región es famosa por sus playas vírgenes, reservas naturales y biodiversidad única.',
  },
  {
    name: 'Salto',
    address: 'Salto, Uruguay',
    imageUrl: 'cities/salto.jpg',
    latitude: -31.3833,
    longitude: -57.9667,
    description: 'Salto es la capital del departamento de Salto y segunda ciudad más grande del país. Es famosa por sus termas y la represa de Salto Grande.',
  },
  {
    name: 'San José de Mayo',
    address: 'San José de Mayo, Uruguay',
    imageUrl: 'cities/san-jose-de-mayo.jpg',
    latitude: -34.3375,
    longitude: -56.7136,
    description: 'San José de Mayo es la capital del departamento de San José. Es un importante centro agrícola e industrial con rica historia colonial.',
  },
  {
    name: 'Mercedes',
    address: 'Mercedes, Uruguay',
    imageUrl: 'cities/mercedes.jpg',
    latitude: -33.2500,
    longitude: -58.0333,
    description: 'Mercedes es la capital del departamento de Soriano, ubicada a orillas del río Negro. Es conocida como "La Capital del Trigo" por su importancia agrícola.',
  },
  {
    name: 'Tacuarembó',
    address: 'Tacuarembó, Uruguay',
    imageUrl: 'cities/tacuarembo.jpg',
    latitude: -31.7333,
    longitude: -55.9833,
    description: 'Tacuarembó es la capital del departamento de Tacuarembó. Es considerada la cuna del folclore uruguayo y posible lugar de nacimiento de Carlos Gardel.',
  },
  {
    name: 'Treinta y Tres',
    address: 'Treinta y Tres, Uruguay',
    imageUrl: 'cities/treinta-y-tres.jpg',
    latitude: -33.2333,
    longitude: -54.3833,
    description: 'Treinta y Tres es la capital del departamento homónimo. Nombrada en honor a los 33 patriotas que lucharon por la independencia uruguaya.',
  },
  {
    name: 'Atlantida',
    address: 'Atlantida, Uruguay',
    imageUrl: 'cities/atlantida.jpg',
    latitude: -34.5000,
    longitude: -55.7500,
    description: 'Atlantida es una ciudad ubicada en el departamento de Atlantida, Uruguay. Es conocida por su clima cálido y su rica cultura.',
  },
];
